applications/alumnos/urls.py
from django.urls import path
from . import views

app_name='alumno_app'

urlpatterns = [
    path('', views.AlumnoView.as_view(), name='Alumno'),
    path('created/', views.AlumnoCreateView.as_view(), name='Created'),
    path('list/', views.AlumnoListView.as_view(), name='List'),
    path('detail/<pk>/', views.AlumnoDetailView.as_view(), name='Detail'),
    path('update/<pk>/', views.AlumnoUpdateView.as_view(), name='Update'),
    path('delete/<pk>/', views.AlumnoDeleteView.as_view(), name='Delete'),
]

whatsapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.alumnos.urls'))
]

applications/alumnos/models.py
from django.db import models

# Create your models here.


class Servicio(models.Model):
    """Model definition for Servicio."""
    nombre = models.CharField('Nombre del servicio', max_length=20)
    importe = models.IntegerField()
    fecha_pago = models.DateField( auto_now_add=True)
    # TODO: Define fields here

    class Meta:
        """Meta definition for Servicio."""

        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'

    def __str__(self):
        """Unicode representation of Servicio."""
        return f"{self.nombre} {self.id}"

class Alumno(models.Model):
    """Model definition for Alumnos."""

    nombre = models.CharField('Nombre:', max_length=20)
    apellido = models.CharField('Apellido:', max_length=10)
    dni = models.CharField('DNI:', max_length=20)
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)
    # Servicio = models.ManyToManyField(Servicio)
    fecha = models.DateField( auto_now_add=True)
    hora = models.DateTimeField(auto_now_add=True)


    class Meta:
        """Meta definition for Alumnos."""

        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'

    def __str__(self):
        """Unicode representation of Alumnos."""
        return f"{self.nombre} {self.id}"

applications/alumnos/forms.py
from django  import forms
from .models import Alumno


class AlumnoForm(forms.ModelForm):
    """Form definition for Alumno."""

    class Meta:
        """Meta definition for Alumnoform."""

        model = Alumno
        fields = ('__all__')

applications/alumnos/views.py
from django.urls import reverse_lazy
from django.shortcuts import render

from django.views.generic import (
                                TemplateView,
                                CreateView,
                                ListView,
                                DeleteView,
                                UpdateView,
                                DetailView
                                )


from .forms import AlumnoForm
from .models import Alumno
# Create your views here.




class AlumnoView(TemplateView):
    template_name = "alumnos/index.html"
    
    def get_context_data(self, **kwargs):
        context = super(AlumnoView, self).get_context_data(**kwargs)
        context['form']=AlumnoForm
        context['alumnos']=Alumno.objects.all().order_by('-hora')[:4]
        return context
    
    

class AlumnoCreateView(CreateView):
    form_class=AlumnoForm
    success_url='/'




class AlumnoListView(ListView):
    model = Alumno
    template_name = "alumnos/lista.html"
    context_object_name='lista'
    paginate_by=5
    

class AlumnoDetailView(DetailView):
    model = Alumno
    template_name = "alumnos/detail.html"
    


class AlumnoUpdateView(UpdateView):
    model = Alumno
    template_name = "alumnos/update.html"
    fields=('__all__')
    success_url=reverse_lazy('alumno_app:List')


class AlumnoDeleteView(DeleteView):
    model = Alumno
    success_url=reverse_lazy('alumno_app:List')

templates/alumnos/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Detalle Alumno
{% endblock title %}


{% block content %}
    
<div >
    
   <p class="p-50"> Nombre: {{alumno.nombre}}- Servicio: {{alumno.servicio.nombre}} -Precio del servicio: {{alumno.servicio.importe}}</p>
</div>

{% endblock content %}

templates/alumnos/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Registro Alumnos
{% endblock title %}

{% block content %}
    

<header>
    <h1>Alumnos</h1>
</header>
<div class="row">
    <div class="form ">
        <form action="{% url 'alumno_app:Created' %}" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Enviar</button>
                </form>
            </div>
            
            <div class="card ">
                <div class="table">
                    <table border="1">
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>DNI</th>
                            <th>Servicio</th>
                            <th>fecha</th>
                        </tr>
                        {% for i in alumnos %}
                        <tr>
                            <td>{{i.nombre}}</td>
                            <td>{{i.apellido}}</td>
                            <td>{{i.dni}}</td>
                            <td>{{i.servicio}}</td>
                            <td>{{i.hora}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                
                
                
                {% if page_obj %}
                p
                hola
                {% endif %}
                
                
            </div>
        </div>
    </div>
    
    {% endblock content %}

templates/alumnos/lista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Lista Alumnos
{% endblock title %}


{% block content %}
    

<table border="1">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>DNI</th>
            <th>Servicio</th>
            <th>Fecha</th>
            <th>Opciones</th>
        </tr>
        {% for i in lista %}
        <tr>
            <td>{{i.nombre}}</td>
            <td>{{i.apellido}}</td>
            <td>{{i.dni}}</td>
            <td>{{i.servicio.nombre}}</td>
            <td><a href="{% url 'alumno_app:Detail' i.id %}">Detalle</a></td>
            <td><a href="{% url 'alumno_app:Update' i.id %}">Actualizar</a></td>
            <form action="{% url 'alumno_app:Delete' i.id %}" method="POST"> {% csrf_token %}
                <td> <button type="submit"> Eliminar </button></td>
            </form>
            
        </tr>
        
        {% endfor %}
        
    </table>
    
    
    <div class="cell">
        {% if is_paginated %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">primera &laquo;{{age_obj.number}}</a>
                <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                
                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;ultima {{age_obj.number}}</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
    {% endblock content %}
    

templates/alumnos/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update</title>
</head>
<body>
    <form action="" method="POST">{% csrf_token %}

        {{form.as_p}}
        <button type="submit">Actualizar</button>
    </form>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %} {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <nav class="navbar">
            <a href="{% url 'alumno_app:Alumno' %}" class="p-20">Inicio</a>
            <a href="{% url 'alumno_app:List' %}" class="p-20">Lista</a>
        </nav>
        
        {% block content %}
            
        {% endblock content %}
            
    </div>
    
</body>
</html>